const pageTexts = {
  userName: "test",
  password: "q1w2e3",
  errorTextLoginPage: "The form is not valid. Please check for errors",
  welcomeTextPersonalAccountPage: "Welcome to the administration",
  createUserEmail: "test@mail.ru",
  createUserFirstName: "Тест",
  createUserLastName: "Тестовый",
  createUserPassword: "qwe123ASD",
  createUserTextSuccess: "Element created",
  createUserDeleteButton: "Delete",
  createUserShow: "Show",
  createUserEditButton: "Edit",
  editUserEmail: "emailedit@yandex.ru",
  editUserFirstName: "Nameedit",
  editUserLastName: "Lastnameedit",
  editUserPassword: "Passwordrdit",
  createStatusName: "TestName",
  createStatusSlug: "TestSlug",
  createLabelsName: "TestLabel",
  editStatusName: "TestNameEdit",
  editStatusSlug: "TestSlugEdit",
  editLabelsName: "TestLabelEdit",
  userForDelete1: "1 john@google",
  userForDelete1: "2 jack@yahoo.",
  statusForDelete1: "1 Draft draft",
  statusForDelete2: "2 To Review",
  statusForDelete3: "3 To Be Fixed",
  userForDelete1: "1 john@google",
  userForDelete2: "2 jack@yahoo.",
  userForDelete3: "3 jane@gmail.",
  labelsForDelete1: "1 bug",
  labelsForDelete2: "2 feature",
  labelsForDelete3: "3 enhancement",
  createTasksTitle: "TestTitle",
  createTasksContent: "TestContent",
  assigneeTask: "emily@example.com",
  statusPublished: "Published",
  labelCritical: "critical",
  labelBug: "bug",
  assigneeTaskEdit: "jane@gmail.com",
  tasksTitleEdit: "TestTitleEdit",
  tasksContentEdit: "TestContentEdit",
  statusDraft: "Draft",

  assigneeForFilter: "jane@gmail.com",
  valueAssignee: "Assignee jane@gmail.com",
  clearValue: "Clear value",
  task1: "Task 1 Description of task 1",
  task2: "Task 2 Description of task 2",
  task3: "Task 3 Description of task 3",
  task4: "Task 4 Description of task 4",
  task6: "Task 6 Description of task 6",
  task7: "Task 7 Description of task 7",
  task10: "Task 10 Description of task 10",
  task15: "Task 15 Description of task 15",
};

export default pageTexts;
