const pageTexts = {
  userName: "test",
  password: "q1w2e3",
  errorTextLoginPage: "The form is not valid. Please check for errors",
  welcomeTextPersonalAccountPage: "Welcome to the administration",
  createUserEmail: "test@mail.ru",
  createUserFirstName: "Тест",
  createUserLastName: "Тестовый",
  createUserPassword: "qwe123ASD",
  createUserTextSuccess: "Element created",
  createUserDeleteButton: "Delete",
  createUserShow: "Show",
  createUserEditButton: "Edit",
  editUserEmail: "emailedit@yandex.ru",
  editUserFirstName: "Nameedit",
  editUserLastName: "Lastnameedit",
  editUserPassword: "Passwordrdit",
  createStatusName: "TestName",
  createStatusSlug: "TestSlug",
  createLabelsName: "TestLabel",
  editStatusName: "TestNameEdit",
  editStatusSlug: "TestSlugEdit",
  editLabelsName: "TestLabelEdit",
  userForDelete1: "1 john@google",
  userForDelete1: "2 jack@yahoo.",
  statusForDelete1: "1 Draft draft",
  statusForDelete2: "2 To Review",
  statusForDelete3: "3 To Be Fixed",
  userForDelete1: "1 john@google",
  userForDelete2: "2 jack@yahoo.",
  userForDelete3: "3 jane@gmail.",
  labelsForDelete1: "1 bug",
  labelsForDelete2: "2 feature",
  labelsForDelete3: "3 enhancement",
};

export default pageTexts;
